- hosts: all
  remote_user: root
  tasks:
  - name: apt upgrade
    apt:
      update_cache: yes
      upgrade: yes
  - name: install build requirements
    apt:
      name:
        - make
        - build-essential
